title: This is Malind's Site
author: M Kowalski  
email: malind.nikulski@gmail.com
description: > Welcome to this! I'm learning so much with Github.

# social links
# twitter_username: your-twitter-handle
github_username:  @mekowalski

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
